export const skills = [
  "Semantic & accesible HTML",
  "Markdown",
  "Git",
  "Responsive web Design",
  "React",
  "Java Script: ES6+",
  "Type Script (basics)",
  "GitHub Pull Request & Review",
  "React Hooks",
  "NPM",
  "Styled-Components",
  "React Redux",
  "Redux (Toolkit)",
  "Immutability",
  "Working with API (fetch, axios)",
  "Promises, Async/Await",
  "Error handling",
  "Redux-Saga",
  "React Router",
  "CSS Grid",
  "CSS Flexbox",
  "CSS BEM convetion",
  "Teamwork",
  "Trello",
  "Figma",
  "Scrum",
  "Next.js",
  "GraphQL",
  "Apollo Client",
  "MongoDB",
  "React Context",
  "React Portals",
  "Next hooks",
  "Static Site Generation",
  "Server Side Rendering",
  "API Routes",
  "Next-Auth",
  "CSS modules",
  "CSS variables",
];

export const newSkills = [
  "React Native",
  "More TypeScript",
  "TanStack Query",
  "Mastering my already acquired skills",
];
